# Generated by Django 3.2.13 on 2025-07-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='english_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='pokemon_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='pokemon_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
