# Generated by Django 3.2.13 on 2025-07-17 15:37

import base.models.item_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=base.models.item_models.create_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('pokemon_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('pokemon_name', models.CharField(default='', max_length=50)),
                ('english_name', models.CharField(default='', max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=base.models.item_models.upload_image_to)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='base.pack')),
                ('tags', models.ManyToManyField(to='base.Tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
