# Generated by Django 3.2.13 on 2025-07-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20250718_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='set_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
