# Generated by Django 3.2.13 on 2025-07-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20250724_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='set_code',
            new_name='series_code',
        ),
    ]
