# Generated by Django 3.2.13 on 2025-07-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_set_code_card_series_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='series_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
