# Generated by Django 3.2.13 on 2025-08-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pack_series_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='series_code',
        ),
    ]
