# Generated by Django 3.2.13 on 2025-11-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_slug_category_series_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='会社名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_kana',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='名（フリガナ）'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_kana',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='姓（フリガナ）'),
        ),
    ]
